package main

import "github.com/henyxia/satisfactory-megafactory/models"

func (cfg *config) setData() {
	var items []*models.Item
	itemLimestone := &models.Item{ID: 1, Name: "Limestone", Type: models.ItemTypeItem}
	itemIronOre := &models.Item{ID: 2, Name: "Iron Ore", Type: models.ItemTypeItem}
	itemCopperOre := &models.Item{ID: 3, Name: "Copper Ore", Type: models.ItemTypeItem}
	itemCateriumOre := &models.Item{ID: 4, Name: "Caterium Ore", Type: models.ItemTypeItem}
	itemCoal := &models.Item{ID: 5, Name: "Coal", Type: models.ItemTypeItem}
	itemRawQuartz := &models.Item{ID: 6, Name: "Raw Quartz", Type: models.ItemTypeItem}
	itemSulfur := &models.Item{ID: 7, Name: "Sulfur", Type: models.ItemTypeItem}
	itemBauxite := &models.Item{ID: 8, Name: "Bauxite", Type: models.ItemTypeItem}
	itemSAM := &models.Item{ID: 9, Name: "SAM", Type: models.ItemTypeItem}
	itemUranium := &models.Item{ID: 10, Name: "Uranium", Type: models.ItemTypeItem}
	itemIronIngot := &models.Item{ID: 11, Name: "Iron Ingot", Type: models.ItemTypeItem}
	itemCopperIngot := &models.Item{ID: 12, Name: "Copper Ingot", Type: models.ItemTypeItem}
	itemCateriumIngot := &models.Item{ID: 13, Name: "Caterium Ingot", Type: models.ItemTypeItem}
	itemSteelIngot := &models.Item{ID: 14, Name: "Steel Ingot", Type: models.ItemTypeItem}
	itemAluminumIngot := &models.Item{ID: 15, Name: "Aluminum Ingot", Type: models.ItemTypeItem}
	itemFicsiteIngot := &models.Item{ID: 16, Name: "Ficsite Ingot", Type: models.ItemTypeItem}
	itemConcrete := &models.Item{ID: 17, Name: "Concrete", Type: models.ItemTypeItem}
	itemQuartzCrystal := &models.Item{ID: 18, Name: "Quartz Crystal", Type: models.ItemTypeItem}
	itemSilica := &models.Item{ID: 19, Name: "Silica", Type: models.ItemTypeItem}
	itemCopperPowder := &models.Item{ID: 20, Name: "Copper Powder", Type: models.ItemTypeItem}
	itemPolymerResin := &models.Item{ID: 21, Name: "Polymer Resin", Type: models.ItemTypeItem}
	itemPetroleumCoke := &models.Item{ID: 22, Name: "Petroleum Coke", Type: models.ItemTypeItem}
	itemAluminumScrap := &models.Item{ID: 23, Name: "Aluminum Scrap", Type: models.ItemTypeItem}
	itemAlienProtein := &models.Item{ID: 24, Name: "Alien Protein", Type: models.ItemTypeItem}
	itemAlienDNACapsule := &models.Item{ID: 25, Name: "Alien DNA Capsule", Type: models.ItemTypeItem}
	itemWater := &models.Item{ID: 26, Name: "Water", Type: models.ItemTypeLiquid}
	itemCrudeOil := &models.Item{ID: 27, Name: "Crude Oil", Type: models.ItemTypeLiquid}
	itemHeavyOilResidue := &models.Item{ID: 28, Name: "Heavy Oil Residue", Type: models.ItemTypeLiquid}
	itemFuel := &models.Item{ID: 29, Name: "Fuel", Type: models.ItemTypeLiquid}
	itemLiquidBiofuel := &models.Item{ID: 30, Name: "Liquid Biofuel", Type: models.ItemTypeLiquid}
	itemTurbofuel := &models.Item{ID: 31, Name: "Turbofuel", Type: models.ItemTypeLiquid}
	itemAluminaSolution := &models.Item{ID: 32, Name: "Alumina Solution", Type: models.ItemTypeLiquid}
	itemSulfuricAcid := &models.Item{ID: 33, Name: "Sulfuric Acid", Type: models.ItemTypeLiquid}
	itemNitricAcid := &models.Item{ID: 34, Name: "Nitric Acid", Type: models.ItemTypeLiquid}
	itemDissolvedSilica := &models.Item{ID: 35, Name: "Dissolved Silica", Type: models.ItemTypeLiquid}
	itemNitrogenGas := &models.Item{ID: 36, Name: "Nitrogen Gas", Type: models.ItemTypeGas}
	itemRocketFuel := &models.Item{ID: 37, Name: "Rocket Fuel", Type: models.ItemTypeGas}
	itemIonizedFuel := &models.Item{ID: 38, Name: "Ionized Fuel", Type: models.ItemTypeGas}
	itemDarkMatterResidue := &models.Item{ID: 39, Name: "Dark Matter Residue", Type: models.ItemTypeGas}
	itemExcitedPhotonicMatter := &models.Item{ID: 40, Name: "Excited Photonic Matter", Type: models.ItemTypeGas}
	itemIronRod := &models.Item{ID: 41, Name: "Iron Rod", Type: models.ItemTypeItem}
	itemScrews := &models.Item{ID: 42, Name: "Screws", Type: models.ItemTypeItem}
	itemIronPlate := &models.Item{ID: 43, Name: "Iron Plate", Type: models.ItemTypeItem}
	itemReinforcedIronPlate := &models.Item{ID: 44, Name: "Reinforced Iron Plate", Type: models.ItemTypeItem}
	itemCopperSheet := &models.Item{ID: 45, Name: "Copper Sheet", Type: models.ItemTypeItem}
	itemAlcladAluminumSheet := &models.Item{ID: 46, Name: "Alclad Aluminum Sheet", Type: models.ItemTypeItem}
	itemAluminumCasing := &models.Item{ID: 47, Name: "Aluminum Casing", Type: models.ItemTypeItem}
	itemSteelPipe := &models.Item{ID: 48, Name: "Steel Pipe", Type: models.ItemTypeItem}
	itemSteelBeam := &models.Item{ID: 49, Name: "Steel Beam", Type: models.ItemTypeItem}
	itemEncasedIndustrialBeam := &models.Item{ID: 50, Name: "Encased Industrial Beam", Type: models.ItemTypeItem}
	itemModularFrame := &models.Item{ID: 51, Name: "Modular Frame", Type: models.ItemTypeItem}
	itemHeavyModularFrame := &models.Item{ID: 52, Name: "Heavy Modular Frame", Type: models.ItemTypeItem}
	itemFusedModularFrame := &models.Item{ID: 53, Name: "Fused Modular Frame", Type: models.ItemTypeItem}
	itemFicsiteTrigon := &models.Item{ID: 54, Name: "Ficsite Trigon", Type: models.ItemTypeItem}
	itemFabric := &models.Item{ID: 55, Name: "Fabric", Type: models.ItemTypeItem}
	itemPlastic := &models.Item{ID: 56, Name: "Plastic", Type: models.ItemTypeItem}
	itemRubber := &models.Item{ID: 57, Name: "Rubber", Type: models.ItemTypeItem}
	itemRotor := &models.Item{ID: 58, Name: "Rotor", Type: models.ItemTypeItem}
	itemStator := &models.Item{ID: 59, Name: "Stator", Type: models.ItemTypeItem}
	itemBattery := &models.Item{ID: 60, Name: "Battery", Type: models.ItemTypeItem}
	itemMotor := &models.Item{ID: 61, Name: "Motor", Type: models.ItemTypeItem}
	itemHeatSink := &models.Item{ID: 62, Name: "Heat Sink", Type: models.ItemTypeItem}
	itemCoolingSystem := &models.Item{ID: 63, Name: "Cooling System", Type: models.ItemTypeItem}
	itemTurboMotor := &models.Item{ID: 64, Name: "Turbo Motor", Type: models.ItemTypeItem}
	itemWire := &models.Item{ID: 65, Name: "Wire", Type: models.ItemTypeItem}
	itemCable := &models.Item{ID: 66, Name: "Cable", Type: models.ItemTypeItem}
	itemQuickwire := &models.Item{ID: 67, Name: "Quickwire", Type: models.ItemTypeItem}
	itemCircuitBoard := &models.Item{ID: 68, Name: "Circuit Board", Type: models.ItemTypeItem}
	itemAILimiter := &models.Item{ID: 69, Name: "AI Limiter", Type: models.ItemTypeItem}
	itemHighSpeedConnector := &models.Item{ID: 70, Name: "High-Speed Connector", Type: models.ItemTypeItem}
	itemReanimatedSAM := &models.Item{ID: 71, Name: "Reanimated SAM", Type: models.ItemTypeItem}
	itemSAMFluctuator := &models.Item{ID: 72, Name: "SAM Fluctuator", Type: models.ItemTypeItem}
	itemComputer := &models.Item{ID: 73, Name: "Computer", Type: models.ItemTypeItem}
	itemSupercomputer := &models.Item{ID: 74, Name: "Supercomputer", Type: models.ItemTypeItem}
	itemRadioControlUnit := &models.Item{ID: 75, Name: "Radio Control Unit", Type: models.ItemTypeItem}
	itemCrystalOscillator := &models.Item{ID: 76, Name: "Crystal Oscillator", Type: models.ItemTypeItem}
	itemSuperpositionOscillator := &models.Item{ID: 77, Name: "Superposition Oscillator", Type: models.ItemTypeItem}
	itemDiamonds := &models.Item{ID: 78, Name: "Diamonds", Type: models.ItemTypeItem}
	itemTimeCrystal := &models.Item{ID: 79, Name: "Time Crystal", Type: models.ItemTypeItem}
	itemDarkMatterCrystal := &models.Item{ID: 80, Name: "Dark Matter Crystal", Type: models.ItemTypeItem}
	itemSingularityCell := &models.Item{ID: 81, Name: "Singularity Cell", Type: models.ItemTypeItem}
	itemNeuralQuantumProcessor := &models.Item{ID: 82, Name: "Neural-Quantum Processor", Type: models.ItemTypeItem}
	itemAlienPowerMatrix := &models.Item{ID: 83, Name: "Alien Power Matrix", Type: models.ItemTypeItem}
	itemEmptyCanister := &models.Item{ID: 84, Name: "Empty Canister", Type: models.ItemTypeItem}
	itemEmptyFluidTank := &models.Item{ID: 85, Name: "Empty Fluid Tank", Type: models.ItemTypeItem}
	itemPressureConversionCube := &models.Item{ID: 86, Name: "Pressure Conversion Cube", Type: models.ItemTypeItem}
	itemPackagedWater := &models.Item{ID: 87, Name: "Packaged Water", Type: models.ItemTypeItem}
	itemPackagedAluminaSolution := &models.Item{ID: 88, Name: "Packaged Alumina Solution", Type: models.ItemTypeItem}
	itemPackagedSulfuricAcid := &models.Item{ID: 89, Name: "Packaged Sulfuric Acid", Type: models.ItemTypeItem}
	itemPackagedNitricAcid := &models.Item{ID: 90, Name: "Packaged Nitric Acid", Type: models.ItemTypeItem}
	itemPackagedNitrogenGas := &models.Item{ID: 91, Name: "Packaged Nitrogen Gas", Type: models.ItemTypeItem}
	itemLeaves := &models.Item{ID: 92, Name: "Leaves", Type: models.ItemTypeItem}
	itemMycelia := &models.Item{ID: 93, Name: "Mycelia", Type: models.ItemTypeItem}
	itemFlowerPetals := &models.Item{ID: 94, Name: "Flower Petals", Type: models.ItemTypeItem}
	itemWood := &models.Item{ID: 95, Name: "Wood", Type: models.ItemTypeItem}
	itemBiomass := &models.Item{ID: 96, Name: "Biomass", Type: models.ItemTypeItem}
	itemCompactedCoal := &models.Item{ID: 97, Name: "Compacted Coal", Type: models.ItemTypeItem}
	itemPackagedOil := &models.Item{ID: 98, Name: "Packaged Oil", Type: models.ItemTypeItem}
	itemPackagedHeavyOilResidue := &models.Item{ID: 99, Name: "Packaged Heavy Oil Residue", Type: models.ItemTypeItem}
	itemSolidBiofuel := &models.Item{ID: 100, Name: "Solid Biofuel", Type: models.ItemTypeItem}
	itemPackagedFuel := &models.Item{ID: 101, Name: "Packaged Fuel", Type: models.ItemTypeItem}
	itemPackagedLiquidBiofuel := &models.Item{ID: 102, Name: "Packaged Liquid Biofuel", Type: models.ItemTypeItem}
	itemPackagedTurbofuel := &models.Item{ID: 103, Name: "Packaged Turbofuel", Type: models.ItemTypeItem}
	itemPackagedRocketFuel := &models.Item{ID: 104, Name: "Packaged Rocket Fuel", Type: models.ItemTypeItem}
	itemPackagedIonizedFuel := &models.Item{ID: 105, Name: "Packaged Ionized Fuel", Type: models.ItemTypeItem}
	itemUraniumFuelRod := &models.Item{ID: 106, Name: "Uranium Fuel Rod", Type: models.ItemTypeItem}
	itemPlutoniumFuelRod := &models.Item{ID: 107, Name: "Plutonium Fuel Rod", Type: models.ItemTypeItem}
	itemBlackPowder := &models.Item{ID: 108, Name: "Black Powder", Type: models.ItemTypeItem}
	itemSmokelessPowder := &models.Item{ID: 109, Name: "Smokeless Powder", Type: models.ItemTypeItem}
	itemGasFilter := &models.Item{ID: 110, Name: "Gas Filter", Type: models.ItemTypeItem}
	itemColorCartridge := &models.Item{ID: 111, Name: "Color Cartridge", Type: models.ItemTypeItem}
	itemBeacon := &models.Item{ID: 112, Name: "Beacon", Type: models.ItemTypeItem}
	itemIodineInfusedFilter := &models.Item{ID: 113, Name: "Iodine-Infused Filter", Type: models.ItemTypeItem}
	itemIronRebar := &models.Item{ID: 114, Name: "Iron Rebar", Type: models.ItemTypeItem}
	itemStunRebar := &models.Item{ID: 115, Name: "Stun Rebar", Type: models.ItemTypeItem}
	itemShatterRebar := &models.Item{ID: 116, Name: "Shatter Rebar", Type: models.ItemTypeItem}
	itemExplosiveRebar := &models.Item{ID: 117, Name: "Explosive Rebar", Type: models.ItemTypeItem}
	itemRifleAmmo := &models.Item{ID: 118, Name: "Rifle Ammo", Type: models.ItemTypeItem}
	itemHomingRifleAmmo := &models.Item{ID: 119, Name: "Homing Rifle Ammo", Type: models.ItemTypeItem}
	itemTurboRifleAmmo := &models.Item{ID: 120, Name: "Turbo Rifle Ammo", Type: models.ItemTypeItem}
	itemNobelisk := &models.Item{ID: 121, Name: "Nobelisk", Type: models.ItemTypeItem}
	itemGasNobelisk := &models.Item{ID: 122, Name: "Gas Nobelisk", Type: models.ItemTypeItem}
	itemPulseNobelisk := &models.Item{ID: 123, Name: "Pulse Nobelisk", Type: models.ItemTypeItem}
	itemClusterNobelisk := &models.Item{ID: 124, Name: "Cluster Nobelisk", Type: models.ItemTypeItem}
	itemNukeNobelisk := &models.Item{ID: 125, Name: "Nuke Nobelisk", Type: models.ItemTypeItem}
	itemElectromagneticControlRod := &models.Item{ID: 126, Name: "Electromagnetic Control Rod", Type: models.ItemTypeItem}
	itemEncasedUraniumCell := &models.Item{ID: 127, Name: "Encased Uranium Cell", Type: models.ItemTypeItem}
	itemNonFissileUranium := &models.Item{ID: 128, Name: "Non-Fissile Uranium", Type: models.ItemTypeItem}
	itemPlutoniumPellet := &models.Item{ID: 129, Name: "Plutonium Pellet", Type: models.ItemTypeItem}
	itemEncasedPlutoniumCell := &models.Item{ID: 130, Name: "Encased Plutonium Cell", Type: models.ItemTypeItem}
	itemFicsonium := &models.Item{ID: 131, Name: "Ficsonium", Type: models.ItemTypeItem}
	itemFicsoniumFuelRod := &models.Item{ID: 132, Name: "Ficsonium Fuel Rod", Type: models.ItemTypeItem}
	itemUraniumWaste := &models.Item{ID: 133, Name: "Uranium Waste", Type: models.ItemTypeItem}
	itemPlutoniumWaste := &models.Item{ID: 134, Name: "Plutonium Waste", Type: models.ItemTypeItem}
	itemBluePowerSlug := &models.Item{ID: 135, Name: "Blue Power Slug", Type: models.ItemTypeItem}
	itemYellowPowerSlug := &models.Item{ID: 136, Name: "Yellow Power Slug", Type: models.ItemTypeItem}
	itemPurplePowerSlug := &models.Item{ID: 137, Name: "Purple Power Slug", Type: models.ItemTypeItem}
	itemPowerShard := &models.Item{ID: 138, Name: "Power Shard", Type: models.ItemTypeItem}
	itemFICSITCoupon := &models.Item{ID: 139, Name: "FICSIT Coupon", Type: models.ItemTypeItem}
	itemSmartPlating := &models.Item{ID: 140, Name: "Smart Plating", Type: models.ItemTypeItem}
	itemVersatileFramework := &models.Item{ID: 141, Name: "Versatile Framework", Type: models.ItemTypeItem}
	itemAutomatedWiring := &models.Item{ID: 142, Name: "Automated Wiring", Type: models.ItemTypeItem}
	itemModularEngine := &models.Item{ID: 143, Name: "Modular Engine", Type: models.ItemTypeItem}
	itemAdaptiveControlUnit := &models.Item{ID: 144, Name: "Adaptive Control Unit", Type: models.ItemTypeItem}
	itemAssemblyDirectorSystem := &models.Item{ID: 145, Name: "Assembly Director System", Type: models.ItemTypeItem}
	itemMagneticFieldGenerator := &models.Item{ID: 146, Name: "Magnetic Field Generator", Type: models.ItemTypeItem}
	itemThermalPropulsionRocket := &models.Item{ID: 147, Name: "Thermal Propulsion Rocket", Type: models.ItemTypeItem}
	itemNuclearPasta := &models.Item{ID: 148, Name: "Nuclear Pasta", Type: models.ItemTypeItem}
	itemBiochemicalSculptor := &models.Item{ID: 149, Name: "Biochemical Sculptor", Type: models.ItemTypeItem}
	itemBallisticWarpDrive := &models.Item{ID: 150, Name: "Ballistic Warp Drive", Type: models.ItemTypeItem}
	itemAIExpansionServer := &models.Item{ID: 151, Name: "AI Expansion Server", Type: models.ItemTypeItem}

	// add items in list
	items = append(items, itemLimestone)
	items = append(items, itemIronOre)
	items = append(items, itemCopperOre)
	items = append(items, itemCateriumOre)
	items = append(items, itemCoal)
	items = append(items, itemRawQuartz)
	items = append(items, itemSulfur)
	items = append(items, itemBauxite)
	items = append(items, itemSAM)
	items = append(items, itemUranium)
	items = append(items, itemIronIngot)
	items = append(items, itemCopperIngot)
	items = append(items, itemCateriumIngot)
	items = append(items, itemSteelIngot)
	items = append(items, itemAluminumIngot)
	items = append(items, itemFicsiteIngot)
	items = append(items, itemConcrete)
	items = append(items, itemQuartzCrystal)
	items = append(items, itemSilica)
	items = append(items, itemCopperPowder)
	items = append(items, itemPolymerResin)
	items = append(items, itemPetroleumCoke)
	items = append(items, itemAluminumScrap)
	items = append(items, itemAlienProtein)
	items = append(items, itemAlienDNACapsule)
	items = append(items, itemWater)
	items = append(items, itemCrudeOil)
	items = append(items, itemHeavyOilResidue)
	items = append(items, itemFuel)
	items = append(items, itemLiquidBiofuel)
	items = append(items, itemTurbofuel)
	items = append(items, itemAluminaSolution)
	items = append(items, itemSulfuricAcid)
	items = append(items, itemNitricAcid)
	items = append(items, itemDissolvedSilica)
	items = append(items, itemNitrogenGas)
	items = append(items, itemRocketFuel)
	items = append(items, itemIonizedFuel)
	items = append(items, itemDarkMatterResidue)
	items = append(items, itemExcitedPhotonicMatter)
	items = append(items, itemIronRod)
	items = append(items, itemScrews)
	items = append(items, itemIronPlate)
	items = append(items, itemReinforcedIronPlate)
	items = append(items, itemCopperSheet)
	items = append(items, itemAlcladAluminumSheet)
	items = append(items, itemAluminumCasing)
	items = append(items, itemSteelPipe)
	items = append(items, itemSteelBeam)
	items = append(items, itemEncasedIndustrialBeam)
	items = append(items, itemModularFrame)
	items = append(items, itemHeavyModularFrame)
	items = append(items, itemFusedModularFrame)
	items = append(items, itemFicsiteTrigon)
	items = append(items, itemFabric)
	items = append(items, itemPlastic)
	items = append(items, itemRubber)
	items = append(items, itemRotor)
	items = append(items, itemStator)
	items = append(items, itemBattery)
	items = append(items, itemMotor)
	items = append(items, itemHeatSink)
	items = append(items, itemCoolingSystem)
	items = append(items, itemTurboMotor)
	items = append(items, itemWire)
	items = append(items, itemCable)
	items = append(items, itemQuickwire)
	items = append(items, itemCircuitBoard)
	items = append(items, itemAILimiter)
	items = append(items, itemHighSpeedConnector)
	items = append(items, itemReanimatedSAM)
	items = append(items, itemSAMFluctuator)
	items = append(items, itemComputer)
	items = append(items, itemSupercomputer)
	items = append(items, itemRadioControlUnit)
	items = append(items, itemCrystalOscillator)
	items = append(items, itemSuperpositionOscillator)
	items = append(items, itemDiamonds)
	items = append(items, itemTimeCrystal)
	items = append(items, itemDarkMatterCrystal)
	items = append(items, itemSingularityCell)
	items = append(items, itemNeuralQuantumProcessor)
	items = append(items, itemAlienPowerMatrix)
	items = append(items, itemEmptyCanister)
	items = append(items, itemEmptyFluidTank)
	items = append(items, itemPressureConversionCube)
	items = append(items, itemPackagedWater)
	items = append(items, itemPackagedAluminaSolution)
	items = append(items, itemPackagedSulfuricAcid)
	items = append(items, itemPackagedNitricAcid)
	items = append(items, itemPackagedNitrogenGas)
	items = append(items, itemLeaves)
	items = append(items, itemMycelia)
	items = append(items, itemFlowerPetals)
	items = append(items, itemWood)
	items = append(items, itemBiomass)
	items = append(items, itemCompactedCoal)
	items = append(items, itemPackagedOil)
	items = append(items, itemPackagedHeavyOilResidue)
	items = append(items, itemSolidBiofuel)
	items = append(items, itemPackagedFuel)
	items = append(items, itemPackagedLiquidBiofuel)
	items = append(items, itemPackagedTurbofuel)
	items = append(items, itemPackagedRocketFuel)
	items = append(items, itemPackagedIonizedFuel)
	items = append(items, itemUraniumFuelRod)
	items = append(items, itemPlutoniumFuelRod)
	items = append(items, itemBlackPowder)
	items = append(items, itemSmokelessPowder)
	items = append(items, itemGasFilter)
	items = append(items, itemColorCartridge)
	items = append(items, itemBeacon)
	items = append(items, itemIodineInfusedFilter)
	items = append(items, itemIronRebar)
	items = append(items, itemStunRebar)
	items = append(items, itemShatterRebar)
	items = append(items, itemExplosiveRebar)
	items = append(items, itemRifleAmmo)
	items = append(items, itemHomingRifleAmmo)
	items = append(items, itemTurboRifleAmmo)
	items = append(items, itemNobelisk)
	items = append(items, itemGasNobelisk)
	items = append(items, itemPulseNobelisk)
	items = append(items, itemClusterNobelisk)
	items = append(items, itemNukeNobelisk)
	items = append(items, itemElectromagneticControlRod)
	items = append(items, itemEncasedUraniumCell)
	items = append(items, itemNonFissileUranium)
	items = append(items, itemPlutoniumPellet)
	items = append(items, itemEncasedPlutoniumCell)
	items = append(items, itemFicsonium)
	items = append(items, itemFicsoniumFuelRod)
	items = append(items, itemUraniumWaste)
	items = append(items, itemPlutoniumWaste)
	items = append(items, itemBluePowerSlug)
	items = append(items, itemYellowPowerSlug)
	items = append(items, itemPurplePowerSlug)
	items = append(items, itemPowerShard)
	items = append(items, itemFICSITCoupon)
	items = append(items, itemSmartPlating)
	items = append(items, itemVersatileFramework)
	items = append(items, itemAutomatedWiring)
	items = append(items, itemModularEngine)
	items = append(items, itemAdaptiveControlUnit)
	items = append(items, itemAssemblyDirectorSystem)
	items = append(items, itemMagneticFieldGenerator)
	items = append(items, itemThermalPropulsionRocket)
	items = append(items, itemNuclearPasta)
	items = append(items, itemBiochemicalSculptor)
	items = append(items, itemBallisticWarpDrive)
	items = append(items, itemAIExpansionServer)

	cfg.DB.Save(items)
}
